# Generated by Django 5.1.1 on 2024-09-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='bibliography',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='dating',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='provenance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='reservelocalisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='LendingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('ongoing', models.BooleanField()),
                ('description', models.TextField()),
                ('inventoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryobject')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.room'),
        ),
    ]
