# Generated by Django 5.1.1 on 2024-09-15 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_room_inventoryobject_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryobject',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.room'),
        ),
    ]
