# Generated by Django 5.1.1 on 2024-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_reservelocalisation_inventoryobject_reservelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectphoto',
            name='legend',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
