# Generated by Django 5.1.1 on 2024-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_objectphoto_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectphoto',
            name='thumbnail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
