# Generated by Django 5.1.1 on 2024-09-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_operationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationhistory',
            old_name='startDate',
            new_name='date',
        ),
    ]
