# Generated by Django 5.1.1 on 2024-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_startdate_operationhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhistory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
