# Generated by Django 5.1.1 on 2024-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_lendinghistory_loanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='ongoing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
