# Generated by Django 5.1.1 on 2024-09-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_loanhistory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='files',
            field=models.ManyToManyField(blank=True, to='inventory.objectfile'),
        ),
    ]
