# Generated by Django 5.1.1 on 2024-09-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_objectfile_inventoryobject_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectfile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
