# Generated by Django 5.1.1 on 2024-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_objectfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryobject',
            name='viewable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectfile',
            name='viewable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
