# Generated by Django 5.1.1 on 2024-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryobject_viewable_objectfile_viewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfile',
            name='viewable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
