# Generated by Django 5.1.1 on 2024-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventoryobject_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectphoto',
            name='viewable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
