# Generated by Django 5.1.1 on 2024-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_room_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='viewable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
