# Generated by Django 5.1.1 on 2024-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_objectfile_viewable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='viewable',
        ),
        migrations.AddField(
            model_name='objectfile',
            name='viewable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
